### ISSUE TITLE
Missing exit implementation for ESC

### ISSUE THREAD

**Issue by RubenAstudillo** [glguy/irc-core#10]
Hi, this probably is trivial.

On the README.md says that ESC quits the client. Yet on commit 747e9c7 this was removed and the /exit command was added to `commandEvent`. At the same time the datatype 
```haskell
data EventResult
  = KeepGoing ClientState
  | Exit
```
was added to driver/Main.hs and it was made that the `keyEvent` function decided how to handle it. The problem is that this function never returns the `Exit` constructor. All the branches in the case statement are enclosed on a `more` function (which returns a `KeepGoing`) or passed to the `inputLogic`.

So either the `EventResult` is removed and `keyEvent` is cleaned up a little, only /exit remaining as the sole method of quitting or the exit constructor is added to the results of `keyEvent`. Both solutions are trivial and I myself can do them, but I would like to know what do you think.

**Comment by glguy** [comment]
On line 326 when you commit to a command there is a non-more line:
```haskell
(KEnter   , []     ) -> snd (inputLogic st)
```
This is where Exit can happen currently. The inputLogic could detect an exit command and return `Exit`

**Comment by RubenAstudillo** [comment]
You are right. I missed the forest for the trees. Thank you for your time.
