### ISSUE TITLE
Attempt automatic reconnection

### ISSUE THREAD

**Issue by bitemyapp** [glguy/irc-core#15]
![screenshot from 2016-01-12 10-47-12](https://cloud.githubusercontent.com/assets/320177/12270613/9051bfd8-b91c-11e5-93e6-0b55f8daacec.png)
![screenshot from 2016-01-12 10-47-19](https://cloud.githubusercontent.com/assets/320177/12270615/9249d744-b91c-11e5-9ac1-128a03828ba3.png)

**Comment by glguy** [comment]
You're right, this behavior isn't server specific. I don't currently have any automatic reconnect logic.

**Comment by glguy** [comment]
Yay, closed in less than a year... b32b2031fe3da9139df3479964aaf44d218ed8ca
