### ISSUE TITLE
Multiple servers with the same hostname

### ISSUE THREAD

**Issue by cocreature** [glguy/irc-core#21]
I proxy all my IRC communication via ZNC. I have a separate ZNC network for each server that I connect to (the network is expressed in the username). However, the hostname still stays the same. It would probably make sense to introduce some (optional?) `server-name` field to decouple the hostname from the name used in commands like `connect`.

**Comment by glguy** [comment]
Yeah, separating the name of a server entry from the hostname is a good idea. I'll put something together tomorrow. Thanks for reporting the issue.

**Comment by glguy** [comment]
Fixed by @cocreature  in #22
