### ISSUE TITLE
Implement join channels on connect

### ISSUE THREAD

**Issue by glguy** [glguy/irc-core#4]

**Comment by RubenAstudillo** [comment]
I am implementing this. You can assign me?

**Comment by glguy** [comment]
Some things I was thinking about with this feature:

1) We'll want to be able to specify keys for channels
2) We'll want to rejoin channels when using `/reconnect`
3) The channels we rejoin should probably be the ones we were in before reconnecting
4) If the key changes for a change before we reconnect we should probably use the new key we know.

**Comment by RubenAstudillo** [comment]
I have a preview branch autojoin-channels (I am new to github) on where I add a new `TChan` to `driver` on main.hs where on successfully joining irc commands are queued until the `Mode` response from server is received. I think we can use it to implement 2 & 3 crafting appropriate commands upon disconnect to issue when reconnecting. It needs obviously a clean up though.

**Comment by glguy** [comment]
I'm looking forward to going through your code. I've just been particularly
busy recently.

**Comment by glguy** [comment]
I'd expect that the auto-join hooks could be based on the existing clientAutomation event handlers waiting for the 001 Welcome message to indicate a successful join. Did you consider this route already?

**Comment by glguy** [comment]
6f425ec12fc661ec0c5633ad9197fc891049c325

I've implemented some functionality for scheduling some commands to run at connection time

**Comment by RubenAstudillo** [comment]
I was doing it on succesfully MODE message, but It seems overall upon Welcome message (it was an arbitrary choice). I will rebase my local commits upon 6f425ec and queue the commands on a new `TChan`  the `driver` will listen.

I am just a little busy until Thursday afternoon. But the design will be cleared by then.

**Comment by RubenAstudillo** [comment]
I did read the commit you made. On specifying `connect-cmd:` as raw commands. Can I think your intention by such approach was to build IRC commands `ByteStrings` without any parsing right?. I think this is the economic solution as we don't have to introduce a new ADT with IRC commands nor mess with error messages

**Comment by glguy** [comment]
Yes, the current version at least just takes raw IRC commands to run upon connection. A possible alternative would be for it to take client commands rather than IRC messages. I put this together as a first pass.

**Comment by glguy** [comment]
Full client commands are now supported upon connection
