### ISSUE TITLE
Poll for buddy list

### ISSUE THREAD

**Issue by glguy** [glguy/irc-core#40]
Periodically poll with ISON to check if a configured list of nicks joins or parts

Concerns: Maximum ISON has room for about 460 characters of response, if nick list is long we'll need to spread over multiple messages.

**Comment by KoraggKnightWolf** [comment]
Heya, Koragg/Testah here from freenode. As discussed in #ircv3 it is best if you implement MONITOR for this as it is far less resource intensive (also on the server, reducing the risk of flooding yourself off). MONITOR is already widely adapted and there is also WATCH which is what MONITOR is based upon (at least the InspIRCd version). Using ISON as a fallback incase neither is supported is of course a suitable option. 
MONITOR is negotiated via CAP while WATCH is part of RAW 005 aka RPL_ISUPPORT
Hope this helps not to lose track of what was discussed on IRC!

Regards,

Koragg

**Comment by glguy** [comment]
Now that monitor is supported on freenode I'm closing this in favor of using monitor.
