### ISSUE TITLE
Word wrapping

### ISSUE THREAD

**Issue by tsani** [glguy/irc-core#49]
When a chat message is too long to fit on one line, it is wrapped on per-character basis (by the terminal emulator, I assume -- correct me if it's glirc that does the wrapping). This frequently breaks words across lines and makes reading harder. Would it be possible to wrap chat messages kind of like how irssi does it? Specifically, a line break is inserted only when there is whitespace in the message, so that word boundaries are preserved, and when a line is broken, padding is added to the new line so that its text is aligned with the previous line's?

**Comment by glguy** [comment]
I think would be wonderful to add, I just haven't thought of a nice way to do it given the current way that message lines are stored. I'll have to renew thinking about it.

**Comment by glguy** [comment]
Implemented b7b877f1f568a457d268f31b465cd115c33bf6ba

Padding messages can be achieved using existing configuration fields: `indent-wrapped-lines` and `nick-padding`
