### ISSUE TITLE
Make split layout more dynamic

### ISSUE THREAD

**Issue by Ongy** [glguy/irc-core#50]
Currently the splits are displayed on top of each other.
For wide (16:9) screens, I think it would be nicer to display them next to each other.
Or even have a way to specify split lines, where a window should be split for the next window to be displayed in, so we can get a layout like:

```

|-----|----|
|  M  |    |
|  ai |----|
|  n  |    |
|-----|----|
```

**Comment by glguy** [comment]
Two column mode is now available via F5 or /toggle-layout
