### ISSUE TITLE
OTR support

### ISSUE THREAD

**Issue by clinty** [glguy/irc-core#55]
It would be nice if glirc could do [OTR](https://otr.im/).

**Comment by glguy** [comment]
I don't know much about OTR. Step one would be for someone to develop a library implementing this protocol. Is there such a library yet?

**Comment by glguy** [comment]
I'm thinking that we could use the C library *libotr* and hook it up via the C extension API in glirc

**Comment by glguy** [comment]
The current state of OTR support is listed here https://github.com/glguy/irc-core/wiki/Off-the-Record-(OTR)-Messaging-Support

**Comment by glguy** [comment]
This feature seems to be working now. I think we could easily find more functionality to add, but that can fit in separate tickets as needed
