### ISSUE TITLE
Document log format

### ISSUE THREAD

**Issue by Ekleog** [glguy/irc-core#62]
Everything is in the title, I think a mention of what the logs are stored as would be helpful for people evaluating glirc from afar to know if it fits their needs :) (example in case: me)

**Comment by glguy** [comment]
https://github.com/glguy/irc-core/wiki/Chat-Logging

I hope that helps!

Most glirc users are using a bouncer to get persistent connections and to support connections from multiple hosts. ZNC is particularly well supported by glirc and has logging support internally.

**Comment by Ekleog** [comment]
Great, thanks! Nitpick: the log format for the server buffer isn't made explicit, though I guess it's very similar.

Also, should I deduce from this page that there is no logging of nick/mode changes or join/part/quit/kicks? (when writing [my quassel to weechat migration script](https://github.com/Ekleog/quassel-to-weechat/blob/master/logs.py) I also had specific formats for server messages, info and others, but I can't remember what those were about)

(also, well with weechat I just use my weechat as a bouncer and I `mosh` into the server when I want to access IRC, I don't really like ZNC because I think it's an unneeded piece of software in the chain :) )

**Comment by glguy** [comment]
The server buffer isn't logged, only the things documented as being logged are currently logged. The module that handles logging isn't very complicated at all, so if you want to write more of the events to file it would be quite easy to do so.

https://github.com/glguy/irc-core/blob/v2/src/Client/Log.hs

Here's the region that renders messages to log text. You'd simply want to elaborate more cases than these three if you wanted to see more output to file:

https://github.com/glguy/irc-core/blob/823aeae6d36c6223039cae202c629862110dcbf4/src/Client/Log.hs#L65-L76
