### ISSUE TITLE
Set console title to active window name

### ISSUE THREAD

**Issue by swantzter** [glguy/irc-core#69]
It'd be create if the console title could be changed to reflect the currently active window (e.g `fn:#freenode`)

**Comment by glguy** [comment]
I like this idea. I think we should make the title configurable. I could imagine something like a format string with fields for:

- network name
- window name
- nickname
- some kind of activity
- what else?

**Comment by swantzter** [comment]
Yeah configurability sounds nice. Would it be interesting to be able to show the same tokens as in the action bar (so modes too)?

Maybe an overall indication of new highlights or sum of new messages / highlights (for example `[hl/msg] fn | #freenode`) 

But that list you have sounds comprehensive

**Comment by glguy** [comment]
<img width="628" alt="window-title-example" src="https://user-images.githubusercontent.com/12164/97611630-a90e1b80-19d3-11eb-89de-e4e4576be46d.png">

Including activity will be useful, too. This is what I'm experimenting with now

**Comment by swantzter** [comment]
I like that :+1:

**Comment by glguy** [comment]
I think this is mostly working at this point
