### ISSUE TITLE
Statically and dynamically remove channels from M-# shortcut

### ISSUE THREAD

**Issue by swantzter** [glguy/irc-core#70]
I'd like a way to remove a channel from the M-# shortcuts, both in config but preferably also via a command (that would preferably write to config so it's persisted) to re-add it to the shortcuts. I'd prefer to have to remove it from config/re-run that command

**Comment by glguy** [comment]
Choices I've made in making the configuration language more expressive have made it hard to dynamically edit that configuration. I'm interested in supporting this but it's not trivial. I need to think how to persist changes back nicely.

A separate feature of programmatically, dynamically editing settings is separately interesting and I have some ideas.

**Comment by glguy** [comment]
We can do this now with hidden windows and make it persistent with window-hint configuration entries
