### ISSUE TITLE
Nick highlighting is a bit weird sometimes

### ISSUE THREAD

**Issue by swantzter** [glguy/irc-core#77]
(like highlighting `t` in `don't`)

**Comment by glguy** [comment]
Current behavior is to search for runs of nick-characters in a chat message. I'd be interested in a better algorithm. I want to make sure cases like `I heard "glguy was here"` to catch glguy.

**Comment by swantzter** [comment]
What about requiring 2 or more chars for nick highlighting. Not that many has a one letter nick and they might as well be highlighted with the standard text colour

**Comment by travankor** [comment]
Isn’t this still an issue if a nick is a substring of a word?

**Comment by glguy** [comment]
No, it only matches whole sequences of nickname characters. `exampleglguy` wouldn't highlight `glguy`, for example.
