### ISSUE TITLE
per-window drafts

### ISSUE THREAD

**Issue by swantzter** [glguy/irc-core#80]
Sometimes when I'm in the middle of typing a longer message something urgent shows up in another channel that I'd like to M-# switch to, write a quick response and then switch back to the message I was composing. but if I M-# switch the input bar isn't cleared

**Comment by glguy** [comment]
If we switch to this I'll want to investigate something like weechat's ability to access either local or global history so the same command can be transplanted to multiple windows.

**Comment by swantzter** [comment]
actually I'm not sure I want this anymore, I've gotten used to the glirc way...

**Comment by travankor** [comment]
I prefer the existing way too.

**Comment by glguy** [comment]
I did spend some time trying to implement this. I couldn't settle on behaviors for history that I was happy with
