### ISSUE TITLE
Readme.md configuration example does not show correct options

### ISSUE THREAD

**Issue by wchresta** [glguy/irc-core#81]
The example in the `README.md` still uses `sasl-username` even though this was changed with https://github.com/glguy/irc-core/commit/7400661b97137a7bafb699b6b521d627ae0ce7f4

This is what the README.md shows:
```
servers:
  * name: "fn"
    hostname:      "chat.freenode.net"
    sasl-username: "someuser"
    sasl-password: "somepass"
```

But these options do not exist anymore.

**Comment by glguy** [comment]
I was afraid to update that because I think a lot of the users are getting an old `glirc` from OS package repositories, but I should probably just commit to keeping things up to do.
