### ISSUE TITLE
Inconsistent rendering and syntax for optional arguments

### ISSUE THREAD

**Issue by swantzter** [glguy/irc-core#82]
In the config for macros, you can mark optional arguments with the suffix `?`, this is in no way rendered in the client. It is also inconsistent with the inbuild commands where optional arguments are rendered within brackets. I prefer the brackets version personally and would appreciate if it's consistent at least in rendering

For example, if i type <kbd>/clear</kbd> it shows `/clear [network] [channel]`

If I want to create a macro for <kbd>/clear</kbd> to <kbd>/cl</kbd> I would specify the arguments with `?` like below

```
* name: "cl"
  arguments: "network? channel?"
  commands: "clear ${0|} ${1|}"
```

If I then type <kbd>/cl</kbd> it renders as `/cl network channel`

**Comment by glguy** [comment]
The other thing implied here is that supporting aliases in the config file would be good.

**Comment by swantzter** [comment]
It wouldn't hurt, but otoh macros is extensible enough for that I think.

perhaps instead of arguments/commands in a macro definition you could have an atom called alias?
