### ISSUE TITLE
Nick tab completion after non-space character

### ISSUE THREAD

**Issue by swantzter** [glguy/irc-core#83]
It would be great if the nick tab completion worked even without having a space (or start of line) before the nick, perhaps by treating any character not allowed in a nick as a space. this would solve for example `(Swan`<kbd>Tab ↹</kbd> or `/mode #channel +b $a:Swa`<kbd>Tab ↹</kbd>

**Comment by glguy** [comment]
This should be working now. bans are actually a special case: they know how to complete hostnames and account names for the current channel
