### ISSUE TITLE
Consecutive nicks

### ISSUE THREAD

**Issue by travankor** [glguy/irc-core#85]
Consecutive nicks should have commas in between them.

**Comment by glguy** [comment]
Which context are you wanting this in?

**Comment by travankor** [comment]
The context is if I'm trying to address multiple people at the same time.

Example:
`nick1, nick2, nick3: what do you think?`

**Comment by travankor** [comment]
So if you do `nick1` and tab complete, then `nick2` and tab complete would automatically add a comma if the nicks are next to each other.

**Comment by glguy** [comment]
I don't see a good way to do this. If I type <kbd>G</kbd><kbd>L</kbd><kbd>Tab</kbd> at the beginning of a line I'm going to expect it to fill in `glguy: ` (with default settings). If I tab complete another nickname afterward I won't want a comma in most cases. The most likely situation is I'm writing something like `glguy: travankor created this ticket`

In the case of tab completions mid-line I don't think it's wrong to ask the user to insert a comma if that's whats desired.

**Comment by travankor** [comment]
>I don't think it's wrong to ask the user to insert a comma if that's whats desired.

Fair enough. This is probably more complexity than it's worth.
