### ISSUE TITLE
Don't autosend multi-line selections

### ISSUE THREAD

**Issue by travankor** [glguy/irc-core#87]
This makes it inadvertently easy to flood rooms with primary selection, for example. Flooding can potentially kick/ban users.

Secondly, I think the user should explicitly authorize sending content.

**Comment by swantzter** [comment]
This sounds a lot like an issue with copy/paste in your terminal emulator

**Comment by travankor** [comment]
How about don't autosend multi-line selections? This is easily reproducible on my end.

Reproduction:
1) Copy a multi-line selection, like:
```
"
test
123
abc
"
```
2) Accidentally paste into buffer
3) All previous selections except the last (in this example the final `"`) are auto-sent by the client

**Comment by glguy** [comment]
Find out if your terminal emulator has bracketed paste. Glirc already handles pastes nicely when the terminal notifies it that you've done one.

**Comment by travankor** [comment]
Installed kitty and it works as expected. Perhaps, this could be documented somewhere? I'm not sure if bracketed paste is ubiquitous yet.

**Comment by travankor** [comment]
>Find out if your terminal emulator has bracketed paste.

I contacted the terminal author, and he insists that it is a bug in the application.

"To enable bracketed paste mode, the application __must__ send `\E[?2004h` to the terminal."

Ref: https://codeberg.org/dnkl/foot/issues/305

**Comment by glguy** [comment]
Most terminals don't appear to require that, but it's good to know. I'll have to see if vty library can support this enabling control sequence.

**Comment by glguy** [comment]
@travankor Looking at the vty source code I can see that it actually does send the control sequence to enable bracketed paste if it believes your terminal supports it.

What was your `TERM` set to when you found it not working?

**Comment by travankor** [comment]
> if it believes your terminal supports it.

My `TERM` was set to `foot`. If I use `TERM=xterm-256color glirc` inside foot, then it works. Secondly, I notice that alacritty with `TERM=alacritty` does not work either.

Note that kitty's terminfo is `xterm-kitty` to avoid these kind of issues :)

**Comment by travankor** [comment]
According to the original terminal author:

"Note: I don't see why one would bother checking terminfo __at all__ before enabling bracketed paste.

All terminals should ignore the `\E[?2004h` sequence if they don't support it.

And to the application there's no difference between having __tried__ to enabled bracketed paste, and not enabling it at all. Hence it's better to just try to enable it on all terminals. If it works it works."

**Comment by glguy** [comment]
Enabling bracketed paste is the vty library's job. Perhaps create an issue on that package to figure out why the enable command isn't being sent to exotic terminal types.

**Comment by travankor** [comment]
Unfortunately, I think this is already a known limitation. https://github.com/jtdaugherty/vty/issues/100#issuecomment-228617507

An easy way to work around this is to force glirc to assume we’re on an Xterm compatible terminal with an alias.
