### ISSUE TITLE
Disable CTCP/DCC

### ISSUE THREAD

**Issue by travankor** [glguy/irc-core#88]
Can there be a toggle to disable CTCP/DCC? Neither are strictly necessary, and they can be used for abuse. `ACTION` could be special-cased since that's probably the only one I use.

**Comment by glguy** [comment]
Which ctcp response are you concerned about? The client doesn't respond to any ctcp message.

**Comment by travankor** [comment]
>The client doesn't respond to any ctcp message.

I think that would be enough.

Can the client automatically ignore DCC requests as well if you toggle it off (since I wouldn’t accept them)?

**Comment by glguy** [comment]
Not at the moment. I'm torn between pulling that functionality out as I don't use it either or finding a nice solution to disabling it at a high-level.
