### ISSUE TITLE
glirc: error while loading shared libraries: libHSglirc-2.38-f3ec2659b33736663a555db766f5b734a9bf4388e5ac34ccb796dca705a43c03-ghc8.10.4.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ghost** [glguy/irc-core#91]
I am using Arch Linux latest version as of April 21 2021 (UTC) and has install Haskell `ghcup` from the official website and the command `cabal install glirc` finished successfully; however, I cannot run `glirc` and this error in the title pops up in the terminal. 
When I check `ldd` this library is missing. So what should I do?

**Comment by glguy** [comment]
People get errors on Arch Linux when they accidentally use the officially packaged Arch Linux packages. Check that you're not doing that. Jump into #haskell and hopefully we can debug your Arch Linux setup.

**Comment by ghost** [comment]
I am sure I have removed all Arch Linux related `ghc` `cabal-install` and `stack` packages.
