### ISSUE TITLE
Cannot build glirc 2.39 from Hackage

### ISSUE THREAD

**Issue by aforemny** [glguy/irc-core#99]
Hi,

- I am having trouble building glirc 2.39 from Hackage: [glirc 2.39 lists](https://hackage.haskell.org/package/glirc-2.39) the following dependencies on Hackage:

  ```
  attoparsec >=0.14 && <0.15
  irc-core >=2.10 && <2.11
  ```

  [irc-core 2.10 lists](https://hackage.haskell.org/package/irc-core-2.10) the following dependencies on Hackage:

  ```
  attoparsec >=0.13 && <0.14
  ```

  Thus, dependencies cannot be solved.

- Additionally, ignoring version bounds and building glirc 2.39 against irc-core 2.10 (from Hackage), I get the following error which seems to correspond to a recent change in irc-core (19aa9a74c255a0adb47b1ac6ada3a8967386dcc0, after irc-core 2.10):

  ```
         > src/Client/Hook/DroneBLRelay.hs:193:3: error:
         >     Not in scope: type constructor or class ‘Source’
  ```

- Building glirc 2.39 against irc-core from the same Git repository succeeds.

Is there anything I am missing?

Thank you for your feedback!

**Comment by glguy** [comment]
Oops, I forgot to do an irc-core 2.11 release. I'll fix that now. Sorry!
